### ISSUE TITLE
LOADING COGS

### ISSUE THREAD

**Issue by h0r1zon** [AlpacaFur/PYBot#3]
# Loading Cogs!
## A great idea
An idea for loading cogs is a thing and I should probably just give you the code but nah Im lazy here's an issue

- Make load commands
- Make unload commands
- Make the bot load loaded cogs on startup
- Make the bot attempt to load any new cogs when they've been inserted on startup
- Make a cog folder

**Comment by AlpacaFur** [comment]
Load and unload commands are complete
The bot already loads cogs on startup
